packetbeat.interfaces.device: en0
packetbeat.protocols.http:
#Add port here if using a port other than 3333.
  ports: [80, 8080, 8000, 5000, 8002, 3333]
  send_all_headers: true
name: test
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]
  # Optional protocol and basic auth credentials.
  #protocol: "https"
  username: "elastic"
  password: "changeme"
logging.selectors: ["*"]
