filebeat.prospectors:
- input_type: log
  paths:
    - tweets.csv
  fields:
    topic: apm
  json.keys_under_root: true

output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "elastic"
  password: "changeme"
  index: "twitter-test"
  template.enabled: true
  template.path: "twitter.json"
  template.overwrite: true