filebeat.prospectors:
- type: log
  fields_under_root: true
  paths:
    - ./ncedc-earthquakes-dataset/earthquakes.txt
  fields:
    type: earthquake

- type: log
  fields_under_root: true
  paths:
    - ./ncedc-earthquakes-dataset/blasts.txt
  fields:
    type: blast

output.elasticsearch:
  hosts: ["localhost:9200"]
  index: "ncedc-earthquakes"
  pipeline: ncedc-earthquakes
  indices:
    - index: "ncedc-earthquakes-earthquake"
      when.equals:
        type: "earthquake"
    - index: "ncedc-earthquakes-blast"
      when.equals:
        type: "blast"
setup.template.enabled: false