#Service Type nodePort
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - nodePort: 31001
    port: 80
    targetPort: 80
