version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.0
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      
  logstash:
    build: logstash
    links:
      - elasticsearch
      - kibana
    ports:
      - 5000:5000
      - 9600:9600

volumes:
  esdata1:
    driver: local
        