filebeat.prospectors:
- input_type: log
  paths:
    - nginx_json_logs
  json.keys_under_root: true
  document_type: logs

output.elasticsearch:
  hosts: ["localhost:9200"]
  index: "nginx_json_elastic"
  pipeline: nginx_json_pipeline

setup.template.enabled: false