apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: dockerlearn2020devops/custom-apache:latest 
  imagePullSecrets:
  - name: regcred
