apiVersion: v1
kind: Secret
metadata:
  name: beats-secrets
data:
  ELASTIC_CLOUD_ID: "b64string"
  ELASTIC_CLOUD_AUTH: "b64string"
  AWS_ACCESS_KEY_ID: "b64string"
  AWS_ACCESS_KEY_SECRET: "b64string"

