###################### Filebeat Configuration Example #########################

#==========================  Modules configuration ============================
name: test

filebeat.modules:
#------------------------------- Auditd Module -------------------------------
- module: auditd
  log:
    prospector:
      include_lines: ['^type=EXECVE']

#================================ Outputs =====================================

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]
  username: "elastic"
  password: "changeme"